### ISSUE TITLE
Add support for multiple objects validation

### ISSUE THREAD

**Issue by fpenim** [EMBL-EBI-SUBS/json-schema-validator#3]
Currently the validator takes this input:
```json
{
  "schema": {},
  "object": {}
}
```
Improve it so that the validator can receive and validate multiple objects.
```json
{
  "schema": {},
  "objects": []
}
```

**Comment by Kerruba** [comment]
Sorry has this been solved in the end?

**Comment by davidrichardson** [comment]
We don't have a clear use case for this in USI, so we decided not to implement it.
